package modele;

public enum Poste {
	
	CONTROLEUR_AERIEN,INGENIEUR_PREPARATEUR_DE_VOL,COORDINATEUR_DE_VOL,RESPONSABLE_D_EXPLOITATION_AEROPORTUAIRE,INGENIEUR_OPERATION_DE_VOL,INGENIEUR_SECURITE_AERIEN,ANALYSTE_DE_VOL,ADMINISTRATEUR;
	
}